### ISSUE TITLE
"returned 1" and doesn't copy

### ISSUE THREAD

**Issue by timtyrrell** [roosta/tmux-fuzzback#1]
Great looking plugin! I gave it a spin and FZF pulls up fine but when I hit "enter" on a line I get the below message and it doesn't seem to copy. Can I provide any more info?

`[my machine]/.tmux/plugins/tmux-fuzzback/scripts/fuzzback.sh' returned 1`

**Comment by roosta** [comment]
Hi! thanks for giving tmux-fuzzback a go :) I'm not entirely sure why it would error out, but fuzzback doesn't actually do any coping, it just moves you to the match so that you can copy whatever you like in tmux copy mode.

Does the script move you to the correct line? I'd like to reproduce the problem, but I'm uncertain what your setup is like, could you provide the tmux version, and fzf version for starters?

**Comment by timtyrrell** [comment]
Ah, I assumed incorrectly, my bad.

**Comment by roosta** [comment]
No worries :) Hope you have a good time. Let me know if I can help with anything at all

**Comment by roosta** [comment]
Closed issue and all, but I worry a bit about the exit status you mentioned. Could you try and run the script from the repo folder
```sh
cd ~/.tmux/plugins/tmux-fuzzback # or wherever you store the plugin
./scripts/fuzzback.sh
```
That should print out an error message pointing to where in the script the issue originates.

**Comment by timtyrrell** [comment]
When I run it there it triggers fzf then when I hit "enter", which I shouldn't do but wanted the error, I get:

```
❯ ./scripts/fuzzback.sh
./scripts/fuzzback.sh: line 256: readarray: command not found
./scripts/fuzzback.sh: line 258: match[1]: unbound variable
```

My settings: https://github.com/timtyrrell/dotfiles/blob/main/.zshrc#L266-L297

**Comment by roosta** [comment]
Think I know a fix, hang on

**Comment by roosta** [comment]
Ok, think you shouldn't exit when you hit enter now.

**Comment by roosta** [comment]
fuzzback is supposed to move you to the line in question, so that you can copy whatever you like when fuzzback puts you in tmux copy mode. I don't think this has worked for you up until now, but it should now...hopefully :)
