### ISSUE TITLE
[Not an Issue] Added colors as an option

### ISSUE THREAD

**Issue by hqkhan** [roosta/tmux-fuzzback#13]
This isn't an issue but something I wanted to share. I added `fuzzback-fzf-color` option to the config to have different colors instead. I was originally thinking of adding an env variable but that would require users to set it only for fuzzback and the code wouldn't be contained. Although I do have colors for normal bash, this option was kinda neat and simple to add. Basically the same way `bind` is added. 

I'd be happy to make a PR if interested or I'm good just keeping it to myself as well but thought I'd share!

(The default colors make it quite hard to see anything for me)

**Comment by roosta** [comment]
Sounds useful! if you could setup a PR I'd really appreciate it :)

**Comment by hqkhan** [comment]
Awesome! I have created the PR #14
