### ISSUE TITLE
Feature request: tmux pop-up option

### ISSUE THREAD

**Issue by timtyrrell** [roosta/tmux-fuzzback#2]
Title says it all ;)

**Comment by roosta** [comment]
Yeah, I can set that up I think :) gimme a little while.

**Comment by roosta** [comment]
Now supported:
tmux.conf
```tmux
set -g @fuzzback-popup 1
```

**Comment by timtyrrell** [comment]
Awesome, it works, can you add a config to let me pass in my own height/width?

`-p 90%,90%`

**Comment by roosta** [comment]
sure, gimme a few minutes, got a build error after this commit for some reason.

**Comment by roosta** [comment]
new option available
```
set -g @fuzzback-popup-size "90%"
```

**Comment by timtyrrell** [comment]
Much better :)

**Comment by eggbean** [comment]
@roosta Does the popup option still work? It's not working for me. I have the lastest version of [`fzf-tmux`](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux).
