### ISSUE TITLE
Strange sorting behaviour

### ISSUE THREAD

**Issue by v-tibi** [roosta/tmux-fuzzback#20]
Sorting seem to be broken for me. In this example I use asdf to list all plugins `asdf plugin-list-all` and trying to look for nodejs plugin in the list. 
![image](https://github.com/roosta/tmux-fuzzback/assets/43302788/6029b7b1-bd77-4106-807d-6598f2d3775c)

Here I piped the output of the command directly into fzf and it works as expected, finding the longest matching substring:

![image](https://github.com/roosta/tmux-fuzzback/assets/43302788/e94427fa-28fd-4916-b280-28ee95769dce)

```
❯ zsh --version
zsh 5.9 (x86_64-ubuntu-linux-gnu)

❯ tmux -V
tmux 3.3a

❯ fzf --version
0.42.0 (d471067)
```

**Comment by roosta** [comment]
I think it was because the `--no-sort` option was set, I don't think I thought that option through, because we want to sort when entering a query. Can you try the branch [fix/results-sorting](https://github.com/roosta/tmux-fuzzback/tree/fix/results-sorting) and confirm that it works how you expect?

**Comment by v-tibi** [comment]
I tried it and compared using fuzzback with piping the output directly into fzf and I can confirm that now they do the same thing. Now i only have to type 2 letters to find nodejs in the list while before it was something like 50th in the list typing out node as search term. In my view It definitely improved the efficiency of searching! 😀

**Comment by v-tibi** [comment]
I experimented a little more with it and what I found is that I would expect fuzzback to list the matches from the current end of the scrollback towards the older outputs. Now it lists the matches from the older ones towards the newer.

**Comment by roosta** [comment]
It lists it in the order that the scrollback lists it, I'm not sure I understand what you mean. When I use `date` a few times, then use fuzzback, it lists things in this order:

![image](https://github.com/roosta/tmux-fuzzback/assets/4509009/dd14a67f-85bd-4c81-9209-50a4ab2bb895)

which is the order I'd expect since that's the order the scrollback lists it.

Anyways, I merged the `--no-sort` removal, good catch.

**Comment by roosta** [comment]
There is the option `set -g @fuzzback-finder-layout 'reverse'`, maybe that will work? otherwise there might be conflicting settings from somewhere else.

**Comment by v-tibi** [comment]
Sorry, my bad, you are right I did not test it thoroughly and in that case it looked like it just does that, going from earlier output to more recent ones. It was one long day for me.  😉

**Comment by roosta** [comment]
No worries :) I'm closing this since the initial issue has been resolved.
