### ISSUE TITLE
Bug: the window shows up for a half a second  then disappears on its own

### ISSUE THREAD

**Issue by MohamedOsman1998** [roosta/tmux-fuzzback#21]
i tried many different config options and tmux versions: 3.2, 3.3a  but it has the same behavior. tried manual and tpm installs also

**Comment by eggbean** [comment]
I think I had this problem too. Are you using Debian or something based on Debian? What does `awk --help` say?

I think you may have `mawk` aliased to `awk`. If you install `gawk`, I think this will solve this problem. Maybe.

**Comment by eggbean** [comment]
I think I had this problem too. Are you using Debian or something based on Debian? What does `awk --version` say?

I think you may have `mawk` aliased to `awk`. If you install `gawk`, I think this will solve this problem. Maybe.

**Comment by MohamedOsman1998** [comment]
```
which mawk
/usr/bin/mawk
~ »
which awk
/usr/bin/awk
~ »
awk --version
GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
```
I am running ubuntu 20.04. Gawk is already installed

**Comment by MohamedOsman1998** [comment]
thanks for the quick response btw!

**Comment by MohamedOsman1998** [comment]
@roosta I have found the issue and edited it manually. There is an option in the fzf-tmux script that you use, that causes  fzf-tmux to crash with no error. perhaps a depreciated option or bug in fzf-tmux. I can submit a pull request with a full workaround if you'd like.

**Comment by roosta** [comment]
Hi @MohamedOsman1998 great that you located the issue. A PR would be awesome.

**Comment by roosta** [comment]
@MohamedOsman1998 if you're not gonna submit a PR, at least let us know what the issue was?

**Comment by MohamedOsman1998** [comment]
Apologies about that, thanks for reminding me i seem to have missed the first response completely. I am making the PR now.

**Comment by MohamedOsman1998** [comment]
#22

**Comment by roosta** [comment]
Merged, thanks!
