### ISSUE TITLE
Option to bind custom key without prefix?

### ISSUE THREAD

**Issue by kevintraver** [roosta/tmux-fuzzback#4]
Right now changing the key assumes a prefix. It would be cool if there is a second option to disable the prefix key.

**Comment by roosta** [comment]
Hi, I added a [new option](f8521dddd165613b76ef4d8cad9ed0c68993a1da) to fuzzback so that you can set a different table that the keybinding goes in.
```
set -g @fuzzback-table 'root'
```
That would be the same as `bind-key -n ...`

**Comment by kevintraver** [comment]
Awesome. Thank you!!
