### ISSUE TITLE
Is it possible to use an alternate search tool such as skim instead of fzf?

### ISSUE THREAD

**Issue by kevintraver** [roosta/tmux-fuzzback#5]
Is it possible to use an alternate search tool such as skim instead of fzf?

I tried the following

```
fzf_popup_cmd() {
  sk-tmux \
    --delimiter=":" \
    --ansi \
    --with-nth="3.." \
    --bind="$2" \
    --no-multi \
    --no-sort \
    --print-query
}
```

but, I believe **skim** has slightly different configuration options.

**Comment by roosta** [comment]
Hi Kevin. It depends, there are certain fzf options I rely on, and if they aren't implemented in skim, that's a problem. I'll look into this when I get the chance, but I cant guarantee I'll get anywhere with it.

**Comment by kevintraver** [comment]
So far it looks like most of the options are either the same or very similar.

The reason I was looking to use **skim** instead of **fzf** is because **skim** has true regex search.

**Comment by roosta** [comment]
True regex support would be great. Another thing I miss in fzf is the ability to report the column number for a partial match. Maybe skim supports that as well... It would enable fuzzback to move to a column even though we don't have a literal match.

Either way, sorry it takes me a while to reply, or address this. I've been busy, but as soon as I get the chance I'll dedicate some time to this.

**Comment by roosta** [comment]
Hi again, so I did some investigating, and turns out it wasn't all that difficult to setup skim as an alternate finder. I've pushed to a new [feature branch](https://github.com/roosta/tmux-fuzzback/tree/feat/skim). 

You can find details about the new variable `fuzzback-finder` in readme. There are also some breaking changes, I renamed some config variables now that fuzzback supports multiple finders.

Give it a try and let me know how it went.

**Comment by roosta** [comment]
If you're curious, it was the option `--no-preview` that isn't in skim, so it failed silently. No worries about that option because I got another feature branch cooking that introduce preview.

Also popup doesn't work with the skim version I got (0.9.4)

**Comment by roosta** [comment]
ok, so I see you removed that option, but the issue I think you hit is that skim doesn't support popup as of yet.

**Comment by roosta** [comment]
hmm, it says it supports it
```
usage: sk-tmux [LAYOUT OPTIONS] [--] [SK OPTIONS]

  LAYOUT OPTIONS:
    (default layout: -d 50%)

    Popup window (requires tmux 3.2 or above):
      -p [WIDTH[%][,HEIGHT[%]]]  (default: 50%)
      -w WIDTH[%]
      -h HEIGHT[%]
      -x COL
      -y ROW

    Split pane:
      -u [HEIGHT[%]]             Split above (up)
      -d [HEIGHT[%]]             Split below (down)
      -l [WIDTH[%]]              Split left
      -r [WIDTH[%]]              Split right
```
But I'm unable to open any popup, fuzzback or otherwise.
