### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by hqkhan** [roosta/tmux-fuzzback#9]
Is this still maintained? I couldn't get the `prefix`+ `?` to do anything when I installed it. I installed via tpm and couldn't get anything. I changed keybind from README but it still didn't do anything.

I tried using `feat/preview` branch but still couldn't get any response. Any idea as to what I'm missing?

**Comment by eggbean** [comment]
Are you sure you completed installation using tpm with `prefix`+`I` (capital)? What version of tmux are you using?

I'm currently having a problem with it at the moment. The pane appears very briefly and then disappears. It used to work, so I need to find the problem in my config.

**Comment by roosta** [comment]
Its still maintained, just been busy with other project. If there are breaking changes I'll get it fixed promptly. Look out for an update during next week. I'll also try and merge some feature branches, one of which includes the preview.

EDIT: I use it myself every day, I haven't noticed anything but the CI is failing, and I was afraid that would propagate.

**Comment by hqkhan** [comment]
My tmux version is `tmux next-3.4`. 

@eggbean, yes, I did install it with `prefix` + `I`. I tried changing branches from main to `feat/preview` in the repo that tpm cloned for me but for some reason that branch was not visible. Only when I manually cloned could I change branches. But changing branches and issuing the `run-shell` command doesn't do anything. To add, even in `main` I can't get the keybind to work. 

I tried changing keybind but nothing happens. Maybe something with my tmux version?

**Comment by eggbean** [comment]
It's not working for me on Widows (WSL) at the moment but works fine on Linux. I will look into why once this new version comes out in a few days.

Maybe try deleting your `$XDG_DATA_HOME/tmux/plugins` directory and try installing again?

**Comment by roosta** [comment]
Great, appreciate it @eggbean

**Comment by roosta** [comment]
I'll repopen issue until all OS issues are resolved

**Comment by roosta** [comment]
I'm confused
> Maybe try deleting your $XDG_DATA_HOME/tmux/plugins directory and try installing again?

who is that directed at? Is there still issue with windows install?

**Comment by roosta** [comment]
I might be mixing things up here. I assumed the install issue was related to CI, but maybe not?

**Comment by eggbean** [comment]
It was directed to [hqkhan](https://github.com/hqkhan)

No, I don't think it could be, as it's working fine for my on Linux (freshly installed). I suspect it doesn't work on WSL because of my configuration, which is a bit complicated.

**Comment by roosta** [comment]
I see, let me know what you figure out then. But the original issue is hopefully resolved.

EDIT: Reason I assume that is that the bug I fixed caused fuzzback to be unresponsive, I was able to reproduce the issue on jammy64 ubuntu, with the version @hqkhan commented (next-3.4), the bug basically made nothing happen when trying to activate fuzzback, which does seem like the issue described initially

**Comment by hqkhan** [comment]
@eggbean Thank you for your suggestion as it somehow fixed the issue lol. I am on AL2 which is Fedora linux based from what I know. I removed the folder as suggested and installed all plugins again and voila, it's working now. Or maybe the commit also fixed something. 

@roosta It's working now. Thank you! For future reference for me, what does "CI" stand for?

**Comment by roosta** [comment]
Glad it got resolved @hqkhan

CI stands for Continuous integration, usually a standin for a build/test/release pipeline. In this case I only test, no need to build, or release but you get the idea :)

https://app.travis-ci.com/github/roosta/tmux-fuzzback

**Comment by roosta** [comment]
It runs everytime someone commits to main, helping to ensure that new changes doesn't break something.

**Comment by hqkhan** [comment]
Ah, yes. My brain is too used to seeing CI/CD together that CI alone didn't make sense. Thanks for the clarification
